name: Honeycomb Buildevents
author: Koenraad Verheyden
description: Add observability to your GitHub Actions workflows 

branding:
  icon: activity
  color: yellow

inputs:
  apikey:
    description: API key used to communicate with the Honeycomb API.
    required: true
  dataset:
    description: Honeycomb dataset to use.
    required: true
  job-status:
    description: The job status.
    required: true

#outputs:

runs:
  using: node12
  main: dist/index.js
  post: dist/index.js
